# Generated by Django 4.0.3 on 2023-08-07 15:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pokergame', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='game_participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
